workaround lambda closure
replace:
        lambda checked, my_idx=idx: self.restore(my_idx))
with:
        (lambda my_idx: lambda checked: self.restore(my_idx))(idx))

the former gives the following error in PySide2 upon being called:

    CALL ERROR: Qt exceptions in virtual methods:
    ________________________________________________________________________________
    TypeError: <lambda>() missing 1 required positional argument: 'checked'